# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiamos la solución
COPY WebApp.sln .

# Copiamos todos los proyectos necesarios 
COPY WebApp/WebApp.csproj WebApp/

COPY Shared/Domain.csproj Shared/
COPY WebAppPxy/Service.csproj WebAppPxy/

COPY . .

# Restauramos las dependencias
RUN dotnet restore WebApp.sln

# Publicamos la app en modo Release
WORKDIR /src/WebApp
RUN dotnet publish -c Release -o /app/build

# Etapa de producción
FROM nginx:alpine AS final

# Borramos el contenido por defecto de nginx (opcional pero recomendado)
RUN rm -rf /usr/share/nginx/html/*

# Copiamos los archivos publicados al contenedor de producción
COPY --from=build /app/build/wwwroot /usr/share/nginx/html

# Exponemos el puerto (por si quieres hacerlo explícito)
EXPOSE 80

# Comando por defecto de nginx
CMD ["nginx", "-g", "daemon off;"]
